version: "3.8"

services:
  rasa_fastapi_app:
    build: .
    ports:
      - "5005:5005"  # Puerto para la API de Rasa
      - "5055:5055"  # Puerto para las acciones de Rasa
      - "8000:8000"  # Puerto para FastAPI
    volumes:
      - .:/app  # Sincroniza el directorio local con el contenedor
